title: FX-3
description: Analog pictures taken with the Yashica FX-3
url: https://fx-3.carlosjtacon.com 
permalink: "/:categories/:title"

collections:
  pages:
    output: true
  photos:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "photos"
    values:
      permalink: "/filmstrip/:title"
      layout: "photo"

exclude:
  - "*readme.md"
  - "*.sh"